<?php

namespace app\admin\common;
use app\admin\model\System;
use think\Controller;
use think\Request;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //在公共控制器的初始化方法中，创建一个常量用来判断用户是否已经登录
        define('USER_ID',Session::get('user_id'));

//        //获取网站配置信息
//        $config=$this->getSystem();
//        //获取当前请求对象
//        $request=Request::instance();
//        //查询当前网站开关状态
//        $this->getStatus($request,$config);

    }
    //判断用户是否登录，在后台入口
    protected function isLogin()
    {
        //如果登录常量为null，表示没有登录
        if(is_null(USER_ID)){
            $this->error('未登录，无权访问~~','login/index');

        }
    }

    //如果用户已登录，不允许重复登录
    protected function alreadyLogin()
    {
        //如果登录常量为null，表示没有登录
        if(!is_null(USER_ID)){
            $this->error('请不要重复登录~~','index/index');

        }
    }

    //获取配置信息
//
//    public function getSystem()
//    {
//        return System::get(1);
//    }
//    //判断当前网站前台开启状态
//    //$request请求对象， $config当前配置信息
//    public function getStatus($request,$config){
//        //当前模块不是admin执行关闭操作
//        if($request->modele() !=='admin'){
//            //根据当前配置表中的is_close值进行判断，如果是1关闭，0则开启。0是默认状态
//            if($config->is_close==1){
//                $this->error('网站已关闭');
//                exit();
//            }
//
//        }
//        //
//    }

}





































